### ISSUE TITLE
Creation of Batch pools with subnets fails on Terra

### ISSUE THREAD

**Issue by giventocode** [microsoft/ga4gh-tes#80] opened 2023-02-10 13:52 UTC
Creating a batch pool with a subnet via Terra WSM fails with the following error:

`"Either the specified VNet does not exist, or the Batch service does not have access to it"`

Additional context:
 - The batch account and the subnet are deployed in an Azure Managed App (AMA).
 - The identity that WSM is using to deploy the batch pool has publisher's/owner access to the AMA.
 - The batch pool can be created without a subnet. 
 
The scope of the issue should include ruling out or confirming if AMA deny-assignments are the culprit and if there's a workaround.

**Comment by vsmalladi** [comment] 2023-02-14 18:52
@giventocode I believe you need to add MI of CoA VM as Network Contributor RBAC at the Resource Group level [CoA #450](https://github.com/microsoft/CromwellOnAzure/issues/450), saw this in my documentation of [Private CoA #535](https://github.com/microsoft/CromwellOnAzure/pull/535)

**Comment by giventocode** [comment] 2023-02-14 19:02
When running on Terra, the TES deployment and security context is different than CoA. The batch pool is created via WSM - the TES user does not have management access to any of the resources, and if ARM management calls are required these are done via WSM/LZ APIs. WSM uses an identity that has owner access to the resource group and all its resources.

**Comment by zykonda** [comment] 2023-03-06 22:38
The error message suggest the Invalid property value.
From requirements list (https://learn.microsoft.com/en-us/azure/batch/batch-virtual-network):
Subnet ID: when specifying the subnet using the Batch APIs, use the resource identifier of the subnet. The subnet identifier is of the form:
/subscriptions/{subscription}/resourceGroups/{group}/providers/Microsoft.Network/virtualNetworks/{network}/subnets/{subnet}
Need to check the actual value passed by WSM as Subnet ID.

**Comment by BMurri** [comment] 2023-12-12 04:22
For deployments managed with the TES (and AFAIK CoA) deployers, the issue of `Invalid property` was addressed in #256. If this is still an issue in Terra, the issue needs to be addressed by fixing the TES server's environment variables in the corresponding HELM chart.

For security context, the WSM's MI needs the `Network Contributor RBAC` as described above, which is also a Terra configuration detail.

I vote this be closed as `external`, unless our documentation is the cause of this issue, in which case we need to improve the documentation.

**Comment by BMurri** [comment] 2023-12-15 21:13
One other issue is that WSM needs to be creating batch pools with the node communication property set to "simplified". IIRC that's not a property that WSM currently allows us to set.

**Closed** 2024-01-26 18:02 UTC
Labels: bug, tobegroomed, TES Priority: P1, Robustness
