### ISSUE TITLE
TES compliance suite builds but fails to run

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#393] opened 2023-09-08 22:28 UTC
**Describe the bug**
When running the TES compliance test in the MSFT ci/cd, instead of the test suite running, the result is as follows:
> 2023-09-08T22:21:27.0355525Z Successfully tagged tes-test-comp:latest
> 2023-09-08T22:21:27.0637036Z 847f4696b300217ae374f40dac290235297fb938e6e5fa1923949096f1710f9e
> 2023-09-08T22:21:28.0975018Z Usage: tes-compliance-suite report [OPTIONS]
> 2023-09-08T22:21:28.0975781Z Try 'tes-compliance-suite report --help' for help.
> 2023-09-08T22:21:28.0976449Z 
> 2023-09-08T22:21:28.0977719Z Error: No such option: --tag
> 2023-09-08T22:21:28.2724250Z Error response from daemon: Could not find the file /app/tes-compliance-suite/results/report.json in container tes-test-container
> 2023-09-08T22:21:28.2749574Z grep: report.json: No such file or directory
> 2023-09-08T22:21:28.2753241Z All TES Compliance tests have passed. 
> 2023-09-08T22:21:28.2763151Z cat: report.json: No such file or directory
> 2023-09-08T22:21:28.2960904Z tes-test-container
> 2023-09-08T22:21:28.4167726Z Untagged: tes-test-comp:latest

**Steps to Reproduce**
Create any PR

**Expected behavior**
The tests run (very helpful when trying to validate conformance to the spec). It is not yet expected that test failures will result in failing this stage of the integration test, though.

**Comment by yuliadub** [comment] 2023-10-11 20:54
duplicate of https://github.com/microsoft/ga4gh-tes/issues/457

**Closed by yuliadub** 2023-10-11 20:54 UTC
Labels: bug, tobegroomed, Code Quality Improvements
