### ISSUE TITLE
Tes-compliance test failure - "Job to retrieve the service info"

### ISSUE THREAD

**Issue by yuliadub** [microsoft/ga4gh-tes#479] opened 2023-10-23 22:48 UTC
**Describe the bug**
This bug is related to tes passing tes compliance tests defined in the following repo: https://github.com/elixir-cloud-aai/openapi-test-runner that checks to see if TES meets the G4GH TES API specification. The test suite is run as part of the tes release integration test in ADO, it is run for every release so you can always go see its results. As of today's report the following test is failing: 

tests/service_info.yml -- https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/tests/service_info.yml
Job to retrieve the service info
Retrieve the TES server info
 "cases": [
2023-10-23T21:40:37.7124299Z                         {
2023-10-23T21:40:37.7124631Z                             "case_name": "status_code",
2023-10-23T21:40:37.7125304Z                             "case_description": "Check if response status code is 200",
2023-10-23T21:40:37.7125989Z                             "log_messages": [
2023-10-23T21:40:37.7126392Z                                 "No logs for success"
2023-10-23T21:40:37.7126856Z                             ],
2023-10-23T21:40:37.7127302Z                             "start_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7127872Z                             "end_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7128313Z                             "status": "PASS",
2023-10-23T21:40:37.7128935Z                             "message": "GET /service-info Successful Response status code"
2023-10-23T21:40:37.7129466Z                         },
2023-10-23T21:40:37.7129724Z                         {
2023-10-23T21:40:37.7130158Z                             "case_name": "response_schema_validation",
2023-10-23T21:40:37.7130674Z                             "case_description": "Check if response matches the model schema",
2023-10-23T21:40:37.7131159Z                             "log_messages": [
**2023-10-23T21:40:37.7132138Z                                 " validation errors for TesServiceInfo\nid\n  field required (type=value_error.missing)\ntype\n  field required (type=value_error.missing)\norganization\n  ..."**
2023-10-23T21:40:37.7133109Z                             ],
2023-10-23T21:40:37.7133493Z                             "start_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7134000Z                             "end_time": "2023-10-23T21:38:44Z",
2023-10-23T21:40:37.7134383Z                             "status": "FAIL",
2023-10-23T21:40:37.7134952Z                             "message": "Response Schema validation failed for GET /service-info"
2023-10-23T21:40:37.7135424Z                         }
2023-10-23T21:40:37.7135648Z                     ]

**Expected behavior**
The 200 response needs to contain an id, as mentioned in the test: https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/tests/service_info.yml

    response:
      200: |
        {
          "id": "uk.ac.ebi.tsc.tesk"
        }

**Comment by vsmalladi** [comment] 2024-04-02 20:52
Now the issue is:

```
Schema Validation Error. Type - TestFailureException. Message - Response Schema validation failed for GET /service-info. Details - 1 validation error for TesServiceInfo contactUrl
invalid or missing URL scheme (type=value_error.url.scheme)
```
Seems to be a an issue with email validation in compliance suite

**Comment by vsmalladi** [comment] 2024-04-16 21:19
Should be fixed by this PR: https://github.com/elixir-cloud-aai/openapi-test-runner/pull/70

**Comment by vsmalladi** [comment] 2024-04-26 16:04
Fixed  with update to TES runner
```
2024-04-25T22:57:41.1813522Z [33m################################     Initiating Test-22 for tests/service_info.yml     #################################[0m
2024-04-25T22:57:41.1945888Z [37mYAML file valid for Test: tests/service_info.yml[0m
2024-04-25T22:57:41.1949079Z [37mRunning tests for sub-job-1 -> service_info[0m
2024-04-25T22:57:41.1957455Z [37mSending GET request to http://tes:***@tesinttest-53111831-5982-04537.southcentralus.cloudapp.azure.com/v1/service-info. Query Parameters - {}[0m
2024-04-25T22:57:41.2660446Z [37mGET /service-info response status code matched[0m
2024-04-25T22:57:41.3186730Z [37mResponse Schema validation successful for GET /service-info[0m
2024-04-25T22:57:41.3204588Z [32mCompliance Test-22 for tests/service_info.yml successful.[0m
```

**Comment by yuliadub** [comment] 2024-04-26 16:23
@vsmalladi huh weird! So it did work for you --- but looks like the current TES ADO run failed to connect to the TES api. 

p.s. the PR doesnt actually change anything about the way we do the response for service info, so what actually fixed it? The change on the test side?

**Closed** 2024-05-20 16:44 UTC
Labels: bug, TES Priority: P2, Spec Compliance
