### ISSUE TITLE
TES does not retry one VM class leads to jobs that specific VM class fail when no VM available 

### ISSUE THREAD

**Issue by jxum2gen** [microsoft/ga4gh-tes#83] opened 2023-02-10 23:05 UTC
**Describe the bug**
We are queuing multiple jobs, which combined have a higher VM requirement than available in our Batch Account. We are specifying a specific VM type. We expect that  tasks would be queued to wait for VMs to be available. Today we see error message with "No VM (out of 449) available with the required resources (vmsize: Standard_VM, preemptible: True) for task id 1234453. The following VM sizes were excluded from consideration because of NodeAllocationFailed error(s) on previous attempts: Standard_VM"

Expected behavior: if we have 100 VMs and we want have a batch of jobs that are submitted that requires 2000 VMs. We want execution to be such that it will run 100 concurrently. When one task finishes and frees up a VM, a tasks on the queue is run. We probably expected some FIFO ordering to the next task is run, unless there is priority concept for tasks. It will take a long time for all the jobs to complete.

**Comment by BMurri** [comment] 2023-02-17 22:08
That error indicates that batch was unable to deploy the VM type requested, which is not a capacity issue, but a configuration issue. `NodeAllocationFailed` usually is caused by the image generation number not being compatible with the VM type.

Which version of TES were you running when you observed this error?

**Comment by jxum2gen** [comment] 2023-02-17 22:27
We were running the version that shipped with CoA 3.0, which should be TES 1.1. 

We don't see that when running fewer job at a time, but we see that when tying to run a lot of jobs concurrently. We are also explicitly specifying the SKU we want. 

When I look thorough the code, it will exclude a sku if it failed to execute on it one time. See https://github.com/microsoft/ga4gh-tes/blob/382fb82d0dc72e56cc0230efc8f13891779d7838/src/TesApi.Web/BatchScheduler.cs#L1506 We don't think that behavior is correct.

**Comment by BMurri** [comment] 2023-02-21 17:22
Because `previouslyFailedVmSizes` pulls from the specific TES task's own logs, that prevents just that task from trying the same VM sku again. Other tasks will try it if it matches the selection algorithm for any of those other tasks.

The next release scales much better, much closer to what you describe as your expected behavior: it will allocate the minimum of the following number of VMs (number of tasks both pending and currently running, quota available) and then run tasks (mostly FIFO, but not strictly) on those VMs until all tasks have run. Once the number of tasks that aren't completed drop under the quota, then the VMs will be released. However, `NodeAllocationFailed` will still fail a task if there aren't other skus that match the selection algorithm.

**Comment by MattMcL4475** [comment] 2023-03-14 04:16
@jxum2gen can you please try the 4.0.0 release and let us know if this is still a problem?  thank you!

**Closed** 2023-04-27 18:12 UTC
Labels: bug
